### PR TITLE
Adding check for iterator in a right place

### PR DESCRIPTION
**Pull request by silwester**
Hi, I had a problem with starting the player. The reason was in code below: it crashed on invoking next() on iterator, but there was no check (actually there was, but the place is wrong, as I can understand). After the fix it starts to work, pls review.

### CODE REVIEW

**Comment by trekawek** [comment]
Hi @silwester!

Thanks for noticing this and for the pull request. The purpose of this for loop is to read the whole iterator and distribute the values over a few channels. For instance, the iterator values can look as follows:

11, 12, 34, 33, 98, 98, 100, 101.

The should be distributed into two arrays:

11, 34, 98, 100
12, 33, 98, 101

The problem is if the number of elements in the iterator module channels is not 0 (eg. for the last sample we don't have a value for the right channel). In this case we should stop iterating.

In the 53ad553759077eef0e1fd65726bb4820fcada681 I extracted the loop into a new method and created the [WaveformTest](analyzer/src/test/java/eu/rekawek/radioblock/sample/WaveformTest.java) covering the new method. I took a [slightly different approach](https://github.com/trekawek/radioblock/blob/53ad553759077eef0e1fd65726bb4820fcada681/analyzer/src/main/java/eu/rekawek/analyzer/sample/Waveform.java#L34-L46) than present in this PR.

The code in this PR seems to only read the first two values of the iterator (for channels=2), so I think it's not the right solution. However, the issue report is obviously correct, so thanks for it!

**Comment by silwester** [comment]
Thanks for explanation, now it's clear what is hapenning :)

After fixing this, I faced a problem, when MultiplexingStrategy.AVERAGE is used in MutingPipe. The problem occurs in CombinedChannelIterator in next() method, because localBuffer still has size 2, but only 1 channel is actually used, so there's NoSuchElement exception when it.next() is called . MultiplexingStrategy.SEPARATE works fine.

Sorry for mixing issues, but this is just to continue the discussion. If you need more details, tell me.

**Comment by trekawek** [comment]
Hi @silwester,
I think I fixed it in #2. Could you confirm?

Thanks,
Tomek

**Comment by silwester** [comment]
@trekawek, yep, now player starts successfully

**Pull request closed without merging**
